### ISSUE TITLE
Audit Log Search not tracking new audit issues

### ISSUE THREAD

**Issue by bfinnegan7675** [Adobe-Consulting-Services/acs-aem-commons#1452]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.4
* [ ] ACS AEM Commons Version: 3.17
* [ ] Reproducible on Latest? yes

### Expected Behavior

I have a site under the path /content/amsurg/knoxvillendocenter. I recently created and deleted a test page under this path. I should see this event come up in the audit log search. 

### Actual Behavior

I have been testing the audit log search by creating/deleting test pages. If I search for any create/delete functions in the audit log search it does not find them, but it finds older stuff. It will not track the page create/delete event even if I do not put in anything for the eventtype. The older stuff is from over a month ago but the newer stuff is from today, and appears in both the audit.log and the audit log uner CRXDE.

### Steps to Reproduce

Create a test page under the knoxvilleendo path, delete the test page and navigate to the audit log search. Try searching for that path under the content root field and observe that the create/delete does not appear, but the test page is showing up in crxde under the /var/audit/com.day.cq.replication/content/amsurg/knoxvilleendocenter folder

### Links

None added - but pasted some screenshots. Please let me know if you need anything else and thanks for your help!

![audit log search](https://user-images.githubusercontent.com/26174459/43799327-75f1edfe-9a4a-11e8-80d7-fea50cfca73f.JPG)
![crxde](https://user-images.githubusercontent.com/26174459/43799328-761215a2-9a4a-11e8-9b0c-baac772009b7.JPG)
![not found](https://user-images.githubusercontent.com/26174459/43799329-762aa20c-9a4a-11e8-8f37-b8a29345deb9.JPG)

**Comment by davidjgonzalez** [comment]
@klcodanr think this your 👶!

**Comment by badvision** [comment]
Wait, there's two Brendan's up in here?  Uh oh.  It's on now. ;P

**Comment by bfinnegan7675** [comment]
![image](https://user-images.githubusercontent.com/26174459/44110720-b0be968a-9fbd-11e8-8ffc-608e9e8db5fc.png)

**Comment by badvision** [comment]
Yeah well I'm the one with commit privileges.  😝

**Comment by bfinnegan7675** [comment]
![image](https://user-images.githubusercontent.com/26174459/44111035-956a4d2e-9fbe-11e8-8447-03cec54fd825.png)

lol!

**Comment by klcodanr** [comment]
I'm almost wondering if this is a indexing issue. Have you tried to see how long it takes before changes appear in the audit log console? Do you have any particular configurations in your Oak indexes?

**Comment by justinedelson** [comment]
definitely sounds like an indexing issue

**Comment by bfinnegan7675** [comment]
Hey @klcodanr 

Sure, it takes about 208ms to find 27 events.

Search Audit Log
Found 27 Audit Events in 208ms

![image](https://user-images.githubusercontent.com/26174459/44169365-66c9bf80-a091-11e8-93d2-6a047f6c114d.png)


If I use the max of 500 and just the /content path it takes about 222ms

![image](https://user-images.githubusercontent.com/26174459/44169355-5fa2b180-a091-11e8-8947-6210ca3d4e7c.png)


If this was an indexing event where would I start to check? I have attached some photos of my cqAuditSearch index

![image](https://user-images.githubusercontent.com/26174459/44169420-9aa4e500-a091-11e8-89a7-6afb8b77fefd.png)


![image](https://user-images.githubusercontent.com/26174459/44169432-a395b680-a091-11e8-9da5-f4e8cc82feb0.png)

**Comment by bfinnegan7675** [comment]
I also checked the audit.log after creating a new test page a few mins ago and found this. It looks like it is writing them to the audit.log itself

15.08.2018 15:47:50.646 [BFinnegan] [session-8721196] Adding node [/content/amsurg/knoxvilleendocenter/en/test]
15.08.2018 15:47:50.646 [BFinnegan] [session-8721196] Adding node [/content/amsurg/knoxvilleendocenter/en/test/jcr:content]
15.08.2018 15:47:50.647 [BFinnegan] [session-8721196] Setting property [/content/amsurg/knoxvilleendocenter/en/test/jcr:content/sling:resourceType]
15.08.2018 15:47:50.647 [BFinnegan] [session-8721196] Setting property [/content/amsurg/knoxvilleendocenter/en/test/jcr:content/jcr:title]
15.08.2018 15:47:50.647 [BFinnegan] [session-8721196] Setting property [/content/amsurg/knoxvilleendocenter/en/test/jcr:content/cq:template]
15.08.2018 15:47:50.647 [BFinnegan] [session-8721196] Setting property [/content/amsurg/knoxvilleendocenter/en/test/jcr:content/cq:lastModified]
15.08.2018 15:47:50.647 [BFinnegan] [session-8721196] Setting property [/content/amsurg/knoxvilleendocenter/en/test/jcr:content/cq:lastModifiedBy]
15.08.2018 15:47:50.648 [BFinnegan] [session-8721196] Setting property [/content/amsurg/knoxvilleendocenter/en/test/jcr:content/jcr:title]
15.08.2018 15:47:50.655 [audit-service] [session-8721205] Adding node [/var/audit/com.day.cq.wcm.core.page/content/amsurg/knoxvilleendocenter/en/test/44933381-3589-49c7-90aa-2181e358bd2b]
15.08.2018 15:47:50.656 [audit-service] [session-8721205] Setting property [/var/audit/com.day.cq.wcm.core.page/content/amsurg/knoxvilleendocenter/en/test/44933381-3589-49c7-90aa-2181e358bd2b/cq:time]
15.08.2018 15:47:50.656 [audit-service] [session-8721205] Setting property [/var/audit/com.day.cq.wcm.core.page/content/amsurg/knoxvilleendocenter/en/test/44933381-3589-49c7-90aa-2181e358bd2b/cq:userid]
15.08.2018 15:47:50.656 [audit-service] [session-8721205] Setting property [/var/audit/com.day.cq.wcm.core.page/content/amsurg/knoxvilleendocenter/en/test/44933381-3589-49c7-90aa-2181e358bd2b/cq:path]
15.08.2018 15:47:50.656 [audit-service] [session-8721205] Setting property [/var/audit/com.day.cq.wcm.core.page/content/amsurg/knoxvilleendocenter/en/test/44933381-3589-49c7-90aa-2181e358bd2b/cq:type]
15.08.2018 15:47:50.656 [audit-service] [session-8721205] Setting property [/var/audit/com.day.cq.wcm.core.page/content/amsurg/knoxvilleendocenter/en/test/44933381-3589-49c7-90aa-2181e358bd2b/cq:category]
15.08.2018 15:47:50.656 [audit-service] [session-8721205] Setting property [/var/audit/com.day.cq.wcm.core.page/content/amsurg/knoxvilleendocenter/en/test/44933381-3589-49c7-90aa-2181e358bd2b/path]
15.08.2018 15:47:50.656 [audit-service] [session-8721205] Setting property [/var/audit/com.day.cq.wcm.core.page/content/amsurg/knoxvilleendocenter/en/test/44933381-3589-49c7-90aa-2181e358bd2b/type]
15.08.2018 15:47:50.656 [audit-service] [session-8721205] Setting property [/var/audit/com.day.cq.wcm.core.page/content/amsurg/knoxvilleendocenter/en/test/44933381-3589-49c7-90aa-2181e358bd2b/userId]
15.08.2018 15:47:50.656 [audit-service] [session-8721205] Setting property [/var/audit/com.day.cq.wcm.core.page/content/amsurg/knoxvilleendocenter/en/test/44933381-3589-49c7-90aa-2181e358bd2b/cq:properties]

**Comment by klcodanr** [comment]
Sorry @bfinnegan7675 -- to be clear, my thought about what is going on here is that Oak has not indexed in the Lucene index AEM uses for searching. Since we're searching the JCR instead of the audit logs the items don't appear until the new nodes are indexed. 

You may want to check the Indexing MBean and investigate Near Real Time Indexing in Oak:
https://jackrabbit.apache.org/oak/docs/query/indexing.html#async-index-lag

**Comment by bfinnegan7675** [comment]
thanks @klcodanr, I'll continue to investigate and post my solution if I can find one here

**Comment by umeshtiwari23** [comment]
@bfinnegan7675 Were you able to resolve this issue? In my case the audit.log is empty but I can see the node is created in the repository and /etc/acs-commons/audit-log-search.html returns zero results.

<img width="1371" alt="Screen Shot 2019-03-12 at 4 05 45 PM" src="https://user-images.githubusercontent.com/8120737/54216101-f1b45080-44e0-11e9-816a-979abbd9ccb5.png">
<img width="1332" alt="Screen Shot 2019-03-12 at 4 05 58 PM" src="https://user-images.githubusercontent.com/8120737/54216104-f24ce700-44e0-11e9-9e75-1f68c3f2b2b5.png">

**Comment by bartoszWesolowski** [comment]
It seems that the index `/oak:index/cqAuditEvent` misses one required parameter `async`. 
To fix that issue try to add this parameter, change reindex property to `false` and save. After this change audit log should be able to find new changes. 

Not working:
![image](https://user-images.githubusercontent.com/9348327/54934256-7b6f0f80-4f1e-11e9-96c2-27761e83893c.png)

Working:
![image](https://user-images.githubusercontent.com/9348327/54934332-9fcaec00-4f1e-11e9-859b-23f8a32ea102.png)

**Comment by bartoszWesolowski** [comment]
I think the best way to fix this is to update crx package with index definition available on https://adobe-consulting-services.github.io/acs-aem-commons/features/audit-log-search/index.html#installing-oak-index
