### ISSUE TITLE
ACS AEM Commons includes extra META-INF/vault files that are generated by plugins

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Consulting-Services/acs-aem-commons#2232]
## Required Information

* [X] AEM Version, including Service Packs, Cumulative Fix Packs, etc: N/A
* [X] ACS AEM Commons Version: 4.4.x
* [X] Reproducible on Latest? yes

### Expected Behavior

It would be nice to have clean META-INF/vault files that are always generated by the maven plugins rather than having the old copy/paste files in SCM (and i think certain values used)
