### ISSUE TITLE
MCP Process manager not tracking jobs

### ISSUE THREAD

**Issue by mcihon-inwk** [Adobe-Consulting-Services/acs-aem-commons#2488]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.5.6.0
* [ ] ACS AEM Commons Version: 4.8.4
* [ ] Reproducible on Latest? yes

### Expected Behavior

When I go to Managed Control Processes and start a new job, I am expecting the job to show up in the process manager, where it would show the details of the process (name, description, status, errors, etc.)

### Actual Behavior

When I go to Managed Control Processes and start a new job, the job starts and runs to completion (or error), however the process manager never updates.  I can find the jobs using CRXDE Lite and check the status that way, however nothing shows up in the process manager.  I have checked the page source to see if it was a rendering issue, however there is no indication that the process manager contains any job/process information when viewing the source of the MCP pages.

### Steps to Reproduce

Browse to ACS AEM Commons, select Managed Control Processes, and start a new job.  This has occurred for all jobs I have created.

**Comment by badvision** [comment]
If you're running through a dispatcher, make sure it's not caching the JSON
url used by the UI.  Ran into that recently.

**Comment by mcihon-inwk** [comment]
Thanks for the suggestion.  I'm a bit new to AEM and ACS Commons.  Would you be able to point me in the direction of any relevant documentation to check this?

**Comment by badvision** [comment]
Open your browser's javascript debug panel.  Look to see if you're getting any javascript errors or if it's loading a .json file correctly in the web requests.  If it's getting the same json file, then the dispatcher needs to be configured not to cache that file (we should get a PR in to fix that from MCP, too) -- if you're getting any other kind of JS error let me know.  If you're not getting any errors but still not seeing anything then you're using an old version of MCP and this is a browser bug I've already fixed; install a newer version of ACS Commons.

**Comment by mcihon-inwk** [comment]
Ok, I'm not seeing any errors.  I started a dry run job and I do see an updated json file signifying the start of the job called jcr:content.start.son.  There is also another json file titled jcr:content.list.json which is always empty on every page load.  I'm guessing this is where the list of completed jobs _should_ populate and this is what you are referring to when you say the dispatcher is caching the json file.  Is this correct?

**jcr:content.start.json**
![image](https://user-images.githubusercontent.com/74873818/100796428-4222be80-33e6-11eb-832b-ea080452dfc7.png)

**jcr:content.list.json**
![image](https://user-images.githubusercontent.com/74873818/100797738-39cb8300-33e8-11eb-9362-031ee6a7e048.png)

**Comment by badvision** [comment]
That is correct -- there must be some other underlying issue preventing that from generating properly.  Did you also deploy the content package for ACS Commons?  There is a folder where MCP tasks are written that needs the proper ACL set up for the service user otherwise things get wonky.

I was wondering if you were using an old version before because we had a similar-acting bug once upon a time but was fixed in 4.3.4 via #2057

-Brendan

**Comment by mcihon-inwk** [comment]
The content package was deployed during the original installation.  I thought this might be a permissions issue as well.  I see all of my tasks generated under /var/acs-commons/mcp/instances just fine - I can access them directly.  I have included screenshots of the access controls setup for two folders below.  

/var/acs-commons/mcp
![image](https://user-images.githubusercontent.com/74873818/100882564-f408cc00-3474-11eb-9b2a-9151f2e4a725.png)

/var/acs-commons/mcp/instances
![image](https://user-images.githubusercontent.com/74873818/100882581-f834e980-3474-11eb-8916-125e1bf05d27.png)

I checked the error.log file in /mnt/crx/author/crx-quickstart/logs/ and found this:

`02.12.2020 14:10:15.016 *WARN* [qtp773834426-1427144] org.apache.jackrabbit.oak.plugins.index.Cursors$TraversingCursor Traversed 100000 nodes with filter Filter(query=select [jcr:path], [jcr:score], * from [nt:base] as a where name(a) = 'jcr:content.list.json' /* xpath: // jcr:content.list.json */, path=*, property=[:localname=[content.list.json]]); consider creating an index or changing the query`

`02.12.2020 14:10:15.161 *WARN* [qtp773834426-1427144] org.apache.jackrabbit.oak.query.ast.SelectorImpl The query read or traversed more than 100000 nodes. To avoid affecting other tasks, processing was stopped. for query select [jcr:path], [jcr:score], * from [nt:base] as a where name(a) = 'jcr:content.list.json' /* xpath: // jcr:content.list.json */`

`02.12.2020 14:10:45.023 *WARN* [qtp773834426-1427121] org.apache.jackrabbit.oak.plugins.index.lucene.LucenePropertyIndex This index is deprecated: /oak:index/lucene; it is used for query Filter(query=select [jcr:path], [jcr:score], * from [nt:base] as a where contains([jcr], 'content.list.json') /* xpath: //*[jcr:contains(@jcr, 'content.list.json')] order by @jcr:score descending */ fullText=jcr:"content.list.json", path=*). Please change the query or the index definitions.`

**Comment by mcihon-inwk** [comment]
Just an update - it does appear to be a caching issue.  Per a suggestion from the Adobe support team I bypassed the dispatcher by accessing the instance directly by IP, when I do so the process manager functions as intended.  I appreciate your help with this. :)

**Comment by badvision** [comment]
Awesome, I'm going to keep this issue open so we track MCP vs Dispatcher as a legitimate issue that requires resolution.
